export default {
    userId: [],
    loggedInUserId: "",
    chatTitles: [],
    pinnedChatTitles: [],
    chatTitlesLoading: false,
    messageData: [],
    activeChat: false,
    chatId: "",
    maxWindowId: 0,
    bookmarksTitle: [],
    firstName: "",
    lastName: "",
    accessToken: "",
    messageId: "",
    emailId: "",
    userRole: "",
    editedChatTitle: "",
    chatTtile: '',
    reasoningTab: false,
    apiChatTitle: "",
    leftPaneOpen: false,
    bookmarksTab: false,
    profileImage: "",
    selectedReasoningData: {},
    isLoading: false,
    typingLoader: false,
    highlightChat: false,
    isGenieMode: false,
    isExistingConversation: false,
    genieChatId: null,
    genieApiConversationId: null,

}